"""remove password auth

Revision ID: 508dad92cf10
Revises: b6819a4225d9
Create Date: 2026-02-26 05:39:53.746055

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '508dad92cf10'
down_revision: Union[str, Sequence[str], None] = 'b6819a4225d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
