"""revert name to display_name

Revision ID: 3c8ab4c93fd2
Revises: 0d3e5c56cde0
Create Date: 2026-02-26 06:18:09.907987

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c8ab4c93fd2'
down_revision: Union[str, Sequence[str], None] = '0d3e5c56cde0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###
